name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Pull to Branches
      run: |
        for branch in $(git branch --format '%(refname:short)' | grep -v 'main'); do
          git pull origin main:$branch
        done
