name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Pull to Branches
      run: |
        for branch in $(git branch -r | grep -v HEAD | grep -v main); do
          git checkout "${branch#origin/}"
          git pull origin main
          git push
          hub pull-request -m "Update from main branch" -b "${branch#origin/}" -h feature/update-all-branches
        done
